@server =http://localhost:4004
@credAdmin = Authorization: Basic elvis.percy.garcia.tincopa@everis.com:ScpPeruEveris2022++



POST {{server}}/v2/ADMINISTRADOR_SRV/Usuario
Content-Type: application/json
{{credAdmin}}

{
        "terminal": "200.48.84.2",
        "fechaRegistro": null,
        "usuarioRegistro": "P000031",
        "fechaActualiza": null,
        "usuarioActualiza": null,
        "activo": true,
        "usuarioId": "06c4da30-6f53-48f5-8292-aca0ee51b158",
        "usuario": "TEST8",
        "clave": "7a3dadc5a9dddcf5194d1eff91c8f8ff:0060bbd18cc4344e",
        "usuarioSap": "00000178",
        "usuarioIas": "P000031",
        "nombre": "JERZY",
        "nombreMostrar": null,
        "correo": "jcornejo@medifarma.com.pe",
        "apellidoPaterno": "CORNEJO",
        "apellidoMaterno": "CORNEJO",
        "tipoDocumento": null,
        "numeroDocumento": "10325693",
        "experiencia": null,
        "telefono": "",
        "Movil": null,
        "seccionId": null,
        "seccionTxt": null,
        "loginSap": "",
        "oMaestraSucursal_codigo": null,
        "oMaestraNivel": "RMD_FABRICACION,RMD_ENVASE,RMD_INSPECCIÓN,RMD_RECUBRIMIENTO,RMD_ACONDICIONADO",
        "oMaestraTipoUsuario_codigo": null,
        "fechaVigInicio": null,
        "fechaVigFin": null
      }