{
	"ActionResult": {
		"_Name": "resultOdata"
	},
	"OnSuccess": "/Armadores/Rules/LineaCredito/Adelantos/ActualizarSolicitudSuccess.js",
	"Properties": {
		"sDetalle": "#Page:SolicitudPendAdelantoDetail/#Control:ntDetDescuento/#Value",
		"sEmbarcacion": "#Page:SolicitudPendAdelantoDetail/#Control:lpEmbarcacion/#SelectedValue",
		"sMontoSolicitado": "#Page:SolicitudPendAdelantoDetail/#Control:spMontoSolicitud/#Value",
		"sPlanta": "#Page:SolicitudPendAdelantoDetail/#Control:lpPlanta/#SelectedValue",
		"sRazonSocial": "#Page:SolicitudPendAdelantoDetail/#Control:spRSocial/#Value",
		"sViaPago": "#Page:SolicitudPendAdelantoDetail/#Control:lpViaPago/#SelectedValue"
	},
	"Target": {
		"EntitySet": "SolicitudPendAdelanto",
		"ReadLink": "{@odata.readLink}",
		"Service": "/Armadores/Services/armadorService.service"
	},
	"ValidationRule": "/Armadores/Rules/LineaCredito/Adelantos/EliminarSolicitudValidationRule.js",
	"_Type": "Action.Type.ODataService.UpdateEntity"
}