{
	"ActionResult": {
		"_Name": "wfResp"
	},
	"ActivityIndicatorText": "Guardando...",
	"OnSuccess": "/Armadores/Rules/LineaCredito/Adelantos/AdelantoSolicitudRespWF.js",
	"ShowActivityIndicator": true,
	"Target": {
		"Path": "/workflow-instances",
		"RequestProperties": {
			"Body": {
				"context": "/Armadores/Rules/LineaCredito/Adelantos/AdelantoSolicitudContextWF.js",
				"definitionId": "lineacredito"
			},
			"Method": "POST"
		},
		"Service": "/Armadores/Services/wfService.service"
	},
	"ValidationRule": "/Armadores/Rules/LineaCredito/Adelantos/AdelantoEmbarcacionValidationRule.js",
	"_Type": "Action.Type.RestService.SendRequest"
}