{
	"ActionResult": {
		"_Name": "oData"
	},
	"Headers": {
		"Content-Type": "application/json"
	},
	"OnSuccess": "/Armadores/Rules/LineaCredito/Adelantos/AdelantoSearchExistResp.js",
	"Properties": [
		"iID"
	],
	"Target": {
		"EntitySet": "SolicitudAdelanto",
		"QueryOptions": "",
		"Service": "/Armadores/Services/armadorService.service"
	},
	"_Type": "Action.Type.ODataService.Read"
}