{
	"ActivityIndicatorText": "Cargando...",
	"NavigationType": "Cross",
	"PageToOpen": "/Armadores/Pages/LineaCredito/Adelantos/EmbarcacionDescuento.page",
	"ShowActivityIndicator": true,
	"ValidationRule": "/Armadores/Rules/LineaCredito/Adelantos/DescuentosValues/DescuentoDetailValidationRule.js",
	"_Type": "Action.Type.Navigation"
}