{
	"ActivityIndicatorText": "Cargando...",
	"OnSuccess": "/Armadores/Actions/Service/s4hOpenService.action",
	"Service": "/Armadores/Services/s4hService.service",
	"ShowActivityIndicator": true,
	"_Type": "Action.Type.ODataService.Create"
}